### ISSUE TITLE
Accessing foreign key related object attribute

### ISSUE THREAD

**Issue by nippo** [makinacorpus/django-geojson#43]
Hi,

Is it possible to access a "geomodel" foreign key related object attribute (not the id) with GeoJSONSerializer().serialize() method?

Thanks!

**Comment by kosner** [comment]
I am interested to access several fields of a Foreign Key on the User.
I am in this case:
```
# model.py
from django.contrib.auth.models import User
class ModelA(models.Model):
    contact = models.ForeignKey(User,db_column='contact', blank=True, null=True, verbose_name="Contact")

# view.py
class ModelAMapLayer(GeoJSONLayerView):
    # Options
    model = ModelA
    properties = ['contact__first_name', 'contact__last_name',] # field resolution doesn't work

# url.py
url(r'^maps/ModelAGeojson.geojson$', login_required(ModelAMapLayer.as_view()), name='ModelAGeojson'),
```

I tested the resolution classic but I have no result
How will I be able to access the different values of the user model in relation ?
