### ISSUE TITLE
2.7.0 missing from PyPI

### ISSUE THREAD

**Issue by sikmir** [makinacorpus/django-geojson#54]
PyPI only has 2.6.0. Could you push up 2.7.0?

**Comment by ugoertz** [comment]
I also have the problem that I cannot install 2.7.0 with pip install -U. While the package is listed by pip search, the new version is missing from the list at https://pypi.python.org/simple/django-geojson/ for some reason.

**Comment by leplatrem** [comment]
I've just pushed it :) Thanks for the feedback !
Enjoy it !
