### ISSUE TITLE
Unicode literal compatibility with Python 3.2

### ISSUE THREAD

**Issue by sikmir** [makinacorpus/django-geojson#55]
django-geojson 2.7.0
```
Running setup.py install for django-geojson
    File ".../lib/python3.2/site-packages/djgeojson/tests.py", line 605
      u'type': u'FeatureCollection',
            ^
  SyntaxError: invalid syntax

    File ".../lib/python3.2/site-packages/djgeojson/fields.py", line 37
      err_msg = u'%s is not a valid GeoJSON geometry type' % geom_type
                                                         ^
  SyntaxError: invalid syntax
```
**New in python 3.0**:
All text is Unicode. [String literals no longer support a leading u or U](https://docs.python.org/3.0/whatsnew/3.0.html#removed-syntax)
**New in python 3.3**:
Support for the unicode legacy literal (u'value') was reintroduced to simplify the maintenance of dual Python 2.x and 3.x codebases. See [PEP 414](https://www.python.org/dev/peps/pep-0414/) for more information.

Possible fix: [Porting tips->Unicode literals](https://docs.djangoproject.com/en/1.8/topics/python3/#unicode-literals).

**Comment by leplatrem** [comment]
Thanks for your feedback! 

I guess we could remove the ``u`` prefixes and try to add ``from __future__ import unicode literals``

Would you like to be part of this and submit a contribution?
