### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1622: ordinal not in range(128)

### ISSUE THREAD

**Issue by valdemarrolfsen** [makinacorpus/django-geojson#59]
Hi, 

I am not able to install this package because of an unicode error:

pip3.4 install --user django-geojson

Collecting django-geojson
  Downloading django-geojson-2.8.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-4rkz06py/django-geojson/setup.py", line 15, in <module>
        open(os.path.join(here, 'CHANGES')).read(),
      File "/usr/local/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1622: ordinal not in range(128)

**Comment by leplatrem** [comment]
Hi,

I cannot reproduce : 
```
$ virtualenv --python=python3.4 env34 
Running virtualenv with interpreter /usr/bin/python3.4
Using base prefix '/usr'
New python executable in env34/bin/python3.4
Also creating executable in env34/bin/python
Installing setuptools, pip...done.

$ source env34/bin/activate
$ pip3.4 install .
Unpacking /home/mathieu/Code/Makina/django-geojson
  Running setup.py (path:/tmp/pip-2z1ugl6y-build/setup.py) egg_info for package from file:///home/mathieu/Code/Makina/django-geojson
    
Downloading/unpacking Django (from django-geojson==2.8.1.dev0)
  Downloading Django-1.8.1-py2.py3-none-any.whl (6.2MB): 6.2MB downloaded
  Storing download in cache at /home/mathieu/Downloads/pip/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fpy2.py3%2FD%2FDjango%2FDjango-1.8.1-py2.py3-none-any.whl
Downloading/unpacking six (from django-geojson==2.8.1.dev0)
  Using download cache from /home/mathieu/Downloads/pip/https%3A%2F%2Fpypi.python.org%2Fpackages%2F3.3%2Fs%2Fsix%2Fsix-1.9.0-py2.py3-none-any.whl
Installing collected packages: Django, six, django-geojson
  Running setup.py install for django-geojson
    
Successfully installed Django six django-geojson
```

And TravisCI is supposed to install and run tests using python 3.4.

In case you wonder, I also tried from pypi : 

```
pip3.4 install django-geojson
Downloading/unpacking django-geojson
  Downloading django-geojson-2.8.0.zip
  Storing download in cache at /home/mathieu/Downloads/pip/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fsource%2Fd%2Fdjango-geojson%2Fdjango-geojson-2.8.0.zip
  Running setup.py (path:/home/mathieu/Code/Makina/django-geojson/env34/build/django-geojson/setup.py) egg_info for package django-geojson
    
Downloading/unpacking Django (from django-geojson)
  Using download cache from /home/mathieu/Downloads/pip/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fpy2.py3%2FD%2FDjango%2FDjango-1.8.1-py2.py3-none-any.whl
Downloading/unpacking six (from django-geojson)
  Using download cache from /home/mathieu/Downloads/pip/https%3A%2F%2Fpypi.python.org%2Fpackages%2F3.3%2Fs%2Fsix%2Fsix-1.9.0-py2.py3-none-any.whl
Installing collected packages: django-geojson, Django, six
  Running setup.py install for django-geojson
    
Successfully installed django-geojson Django six
Cleaning up...
```

@gutard any idea ?

**Comment by valdemarrolfsen** [comment]
I was able to install by cloning the repo, mod the setup.py and then install, so no worries!

**Comment by leplatrem** [comment]
Could you please give us your changes? We would like to prevent other users to face the same problem!
Thanks :)

PS: Was it similar to https://github.com/makinacorpus/django-leaflet/issues/82#issuecomment-100469883 ?

PS2: Today @Natim fixed a similar problem in one of our repos : https://github.com/mozilla-services/cliquet/commit/ab73ee82ac14ceca3be7fe6b907c17c706f69ee7
