### ISSUE TITLE
ValuesQuerySet removed in Django 1.9

### ISSUE THREAD

**Issue by jlesech** [makinacorpus/django-geojson#66]
ValuesQuerySet has been removed in Django 1.9 ([release notes](https://docs.djangoproject.com/en/1.9/releases/1.9/#miscellaneous)).

**Comment by leplatrem** [comment]
Thanks for the feedback!
Please open a pull-request if you need it!

**Comment by mankoell** [comment]
How do I install `ValuesQuerySet` in Django 1.9?

**Comment by tnctrack** [comment]
Having the same issue. 

InvalidTemplateLibrary at /admin/login/
Invalid template library specified. ImportError raised when trying to load 'djgeojson.templatetags.geojson_tags': cannot import name 'ValuesQuerySet'
Request Method:	GET
Request URL:	http://localhost:8000/admin/login/?next=/admin/
Django Version:	1.9.1
Exception Type:	InvalidTemplateLibrary
Exception Value:	
Invalid template library specified. ImportError raised when trying to load 'djgeojson.templatetags.geojson_tags': cannot import name 'ValuesQuerySet'
Exception Location:	/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/template/backends/django.py in get_package_libraries, line 148
Python Executable:	/Library/Frameworks/Python.framework/Versions/3.4/bin/python3
Python Version:	3.4.2

**Comment by AayushB** [comment]
Having the same issue.

InvalidTemplateLibrary at /admin/login/
Invalid template library specified. ImportError raised when trying to load 'djgeojson.templatetags.geojson_tags': cannot import name 'ValuesQuerySet'
Request Method: GET
Request URL: http://localhost:8000/admin/login/?next=/admin/
Django Version: 1.9.1
Exception Type: InvalidTemplateLibrary
Exception Value:

Invalid template library specified. ImportError raised when trying to load 'djgeojson.templatetags.geojson_tags': cannot import name 'ValuesQuerySet'
Exception Location: /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/template/backends/django.py in get_package_libraries, line 148
Python Executable: /Library/Frameworks/Python.framework/Versions/3.4/bin/python3
Python Version: 3.4.2

**Comment by leplatrem** [comment]
It should not be toi much trouble fixing it, feel free to open a pull request!

**Comment by mankoell** [comment]
@leplatrem Isn't there already one? #67

**Comment by jlesech** [comment]
It's the same issue. But test suite is broken and I don't know yet how to solve the problem.

**Comment by mankoell** [comment]
I applied your patch @jlesech manually but still see no `PointField` rendered. :no_entry:

**Comment by zelds** [comment]
`django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'djgeojson.templatetags.geojson_tags': cannot import name 'ValuesQuerySet'`
The same error . How i can fix that ?

**Comment by leplatrem** [comment]
Please?

**Comment by zelds** [comment]
Fix is easy= ) from 
`from django.db.models.query import QuerySet,ValuesQuerySet ` remove ValuesQuerySet

**Comment by leplatrem** [comment]
> Fix is easy

If you are in a hurry, you can fork the repo and point your branch with the quick fix in your pip dependencies.

Otherwise you can encourage @jlesech which is contributing a pull-request that works for every django versions.

**Comment by zelds** [comment]
I`m noob. Just start work with python/Django i know nothing about test.
