### ISSUE TITLE
Polygon import error in 1.9

### ISSUE THREAD

**Issue by afrigeri** [makinacorpus/django-geojson#68]
After updating to 1.9 I got:
 File "/usr/local/lib/python2.7/dist-packages/djgeojson/views.py", line 6, in <module>
    from django.contrib.gis.geos.geometry import Polygon

then I changed to:
from django.contrib.gis.geos import Polygon 

and it seems ok.

Alessandro

**Comment by leplatrem** [comment]
Thanks for this feedback!
Could you please open a pull-request to fix it for everyone?
