### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by chris10an** [makinacorpus/django-geojson#85]
This package has optional [extra dependencies. ](http://pythonhosted.org/setuptools/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies)

Link points to http://pythonhosted.org/setuptools/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies with throws an 404.

**Comment by Gagaro** [comment]
Thanks, fixed in 520d682c3a0ffb5a9982ee801569d201d4c16cfd
