### ISSUE TITLE
Django 2.0: AttributeError: 'CharField' object has no attribute 'rel'

### ISSUE THREAD

**Issue by cgestes** [makinacorpus/django-geojson#91]
field.rel have been changed to field.remote_field in django 2.0.

I didn't check former version.

The error message is:
```
/djgeojson/serializers.py", line 416, in serialize_queryset
    if field.rel is None:
```

**Comment by Gagaro** [comment]
Fixed in https://github.com/makinacorpus/django-geojson/commit/8198f63b706a9790933fa4b7575d6d3da383875f, I'll do a release now.

**Comment by Gagaro** [comment]
2.11.0 has been released

**Comment by cgestes** [comment]
Awesome. Thank you.

I'll try it soon.
